# Generated by Django 4.0 on 2021-12-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=25, null=True)),
                ('region', models.CharField(blank=True, choices=[('east', 'East'), ('west', 'West'), ('north', 'North'), ('south', 'South')], max_length=255, null=True)),
                ('income_group', models.CharField(blank=True, choices=[(1, '0-$25K'), (1, '$25-$70K'), (3, '>$70K')], max_length=255, null=True)),
                ('is_married', models.BooleanField(default=False)),
            ],
        ),
    ]
