# Generated by Django 4.0 on 2021-12-21 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'ordering': ('-id', '-date_purchased')},
        ),
    ]
